name: Preview Deployment Pipeline

on:
  push:
    branches:
      - preview

permissions:
  contents: read

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: https://preview-4.relaysms.afkanerd.de
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Enable Corepack and Use Latest Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Install dependencies
        run: |
          yarn install

      - name: Build project
        run: |
          yarn build

      - name: Securely Copy Artifacts to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "build/*"
          target: ${{ secrets.BUILD_PATH }}
          strip_components: 1
          rm: false

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            echo "============================"
            echo "🚀 Deploy Project ..."
            echo "============================"
            if ! ${{secrets.BUILD_CMD}}; then
              echo "❌ Error deploying project!"
              exit 1
            fi
            echo "==============================="
            echo "✅ Deployment complete"
            echo "==============================="
